meta:
  environment: vault-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: vault_z1
    instances: 1
    networks:
      - name: vault1
        static_ips: (( static_ips(0) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: vault1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.8.0/30
    reserved:
    - 10.244.8.1
    static:
    - 10.244.8.2

  - cloud_properties:
      name: random
    range: 10.244.8.4/30
    reserved:
    - 10.244.8.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.8/30
    reserved:
    - 10.244.8.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.12/30
    reserved:
    - 10.244.8.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.16/30
    reserved:
    - 10.244.8.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.8.20/30
    reserved:
    - 10.244.8.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.24/30
    reserved:
    - 10.244.8.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.28/30
    reserved:
    - 10.244.8.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.32/30
    reserved:
    - 10.244.8.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.8.36/30
    reserved:
    - 10.244.8.37
    static: []
